# Generated by Django 2.2.8 on 2019-12-20 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ram_slots', models.IntegerField()),
                ('max_ram', models.IntegerField()),
                ('integrated_video', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('graphic_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GraphicCard')),
                ('memory1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_slot_1', to='core.Memory')),
                ('memory2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_slot_2', to='core.Memory')),
                ('memory3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_slot_3', to='core.Memory')),
                ('memory4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_slot_4', to='core.Memory')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Motherboard')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Processor')),
            ],
        ),
        migrations.AddField(
            model_name='motherboard',
            name='processor_suported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Processor'),
        ),
    ]
