# Generated by Django 2.2.8 on 2019-12-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='processor_suported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Brand'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Brand'),
        ),
    ]
