# Generated by Django 2.2.8 on 2019-12-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191221_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='graphic_card',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.GraphicCard'),
        ),
        migrations.AlterField(
            model_name='order',
            name='memory2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_slot_2', to='core.Memory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='memory3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_slot_3', to='core.Memory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='memory4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_slot_4', to='core.Memory'),
        ),
    ]
