# Generated by Django 2.2.9 on 2019-12-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191222_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='graphic_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GraphicCard'),
        ),
        migrations.AlterField(
            model_name='order',
            name='graphic_card_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='memory1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='memory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_slot_2', to='core.Memory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='memory2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='memory3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_slot_3', to='core.Memory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='memory3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='memory4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_slot_4', to='core.Memory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='memory4_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='motherboard_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='processor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
